spring:
  application:
    name: first
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
  ai:
    chat:
#      client:
#        enabled: false
#    google:
#      genai:
#        api-key: ${GOOGLE_API_KEY}
#        chat:
#            options:
#                model: gemini-3.5-flash
#                temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: phi4-mini:3.8b
          temperature: 0.7

logging:
  level:
    org:
        springframework:
          ai:
            chat:
              client:
                advisor: DEBUG
